'use client'

import { RingLoader } from '@/app/(app)/components/RingLoader'
import { CSSVariablesResolver, MantineProvider, createTheme, Loader, NavLink } from '@mantine/core'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

const theme = createTheme({
  components: {
    Loader: Loader.extend({
      defaultProps: {
        loaders: { ...Loader.defaultLoaders, ring: RingLoader },
        type: 'ring',
      },
    }),
    NavLink: NavLink.extend({
      styles: {
        root: {
          borderRadius: 'var(--mantine-radius-sm)',
        },
      },
    }),
  },
  headings: {
    sizes: {
      h1: {
        fontWeight: '400',
      },
    },
  },
  spacing: {
    lg: '2rem',
    xl: '3rem',
    xxl: '4.5rem',
  },
})

const resolver: CSSVariablesResolver = (theme) => ({
  variables: {},
  light: {
    '--light-bg-0': theme.colors.gray[0],
    '--success-fill-color': theme.colors.green[6],
  },
  dark: {
    '--light-bg-0': theme.colors.dark[9],
    '--success-fill-color': theme.colors.green[8],
  },
})

export const ThemeProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  return (
    <MantineProvider theme={theme} cssVariablesResolver={resolver}>
      {children}
    </MantineProvider>
  )
}
