'use server'

import { auth } from '@/app/(app)/lib/auth'
import { extractTransactionWithGroq } from '@/lib/extraction/groqProvider'
import { extractTextFromImageBuffer } from '@/lib/ocrProvider'
import { getServerSideURL } from '@/utilities/getURL'
import { headers } from 'next/headers'
import { getPayload } from 'payload'
import config from '~/payload.config'
import {
  generateAutoReferenceNumberBase,
  toAlphabetSuffix,
} from '@/collections/utilities/autoReferenceNumber'
import type { UserConfiguration } from '~/payload-types'

export type TransactionType = 'debit' | 'credit'
export type TransactionStatus = 'completed' | 'failed'

export type BankOption = {
  id: string
  name: string
  shortName?: string
  code: string
}

export type FinancialAccountOption = {
  id: string
  name: string
  code: string
  isDefault?: boolean
  bankId?: string
  bankName?: string
  bankShortName?: string
  startingBalance?: number
  currentBalance?: number
  allocationFunds?: number
  allocatedFunds?: number
}

export type TransactionListItem = {
  receiptImage?: { url?: string }
  id: string
  description: string
  particulars?: string
  transactionType?: TransactionType
  financialAccountId?: string
  financialAccountName?: string
  sourceAccountId?: string
  sourceAccountCode?: string
  sourceAccountName?: string
  destinationAccountId?: string
  destinationAccountCode?: string
  destinationAccountName?: string
  from?: string
  to?: string
  sender?: string
  receiver?: string
  referenceNumber?: string
  isAutoGenerated?: boolean
  isAllocatedFund?: boolean
  isForAllocation?: boolean
  allocatedFunds?: number
  allocatedFundType?: 'completed' | 'returned' | null
  parentTransaction?: string | null
  transactionDate?: string
  amount?: number
  transactionFee?: number
  currentBalance?: number
  runningBalance?: number
  transactionStatus?: TransactionStatus
  createdAt: string
  lastUpdated: string
}

export type TransactionListSortBy = 'date' | 'amount' | 'updated'
export type TransactionListSortOrder = 'asc' | 'desc'

export type GetTransactionsPageParams = {
  page?: number
  pageSize?: number
  search?: string
  financialAccountId?: string | null
  transactionTypes?: TransactionType[]
  transactionStatuses?: TransactionStatus[]
  sourceAccountIds?: string[]
  destinationAccountIds?: string[]
  startDate?: string | null
  endDate?: string | null
  sortBy?: TransactionListSortBy
  sortOrder?: TransactionListSortOrder
}

export type TransactionPageResult = {
  success: boolean
  data: TransactionListItem[]
  pagination?: {
    page: number
    pageSize: number
    totalDocs: number
    totalPages: number
  }
  error?: string
}

export type TransactionFormInput = {
  allocatedFunds?: string
  allocatedFundType?: 'completed' | 'returned' | null // <--- fix type
  transactionDate?: string
  description: string
  particulars?: string
  transactionType?: TransactionType | null
  sourceAccount?: string
  destinationAccount?: string
  financialAccount?: string
  from?: string
  to?: string
  referenceNumber?: string
  isAutoGenerated?: boolean
  amount?: number
  transactionFee?: number
  currentBalance?: number
  transactionStatus?: TransactionStatus | null
  receiptImageId?: string
  rawOcrText?: string
  aiExtractedJson?: string | number | boolean | null | Record<string, unknown> | unknown[]
  extractionConfidence?: number
  isAllocatedFund?: boolean
  isForAllocation?: boolean
  parentTransaction?: string | null
}

export type TransactionDetail = TransactionFormInput & {
  id: string
  receiptImageId?: string
  receiptImageUrl?: string
  receiptImageFileName?: string
  rawOcrText?: string
  extractionConfidence?: number
  aiExtractedJson?: unknown
  isAiGenerated?: boolean
  isUserEdited?: boolean
  runningBalance?: number
  isAutoGenerated?: boolean
  isAllocatedFund?: boolean
  isForAllocation?: boolean
  allocatedFunds?: number
  parentTransaction?: string | null
  allocatedFundType: 'completed' | 'returned' | null | undefined
}

export type ProcessTransactionReceiptResult = {
  success: boolean
  status?: 'idle' | 'processing' | 'partial-success' | 'success' | 'failed'
  rawOcrText?: string
  detectedSourceBankId?: string
  detectedDestinationBankId?: string
  transactionDate?: string
  description?: string
  particulars?: string
  transactionType?: TransactionType
  referenceNumber?: string
  isAutoGenerated?: boolean
  amount?: number
  transactionFee?: number
  transactionStatus?: TransactionStatus
  from?: string
  to?: string
  confidence?: number
  aiExtractedJson?: TransactionFormInput['aiExtractedJson']
  error?: string
  warning?: string
}

export type ReceiptAnalysisResult = {
  success: boolean
  rawOcrText?: string
  detectedSourceBankId?: string
  detectedDestinationBankId?: string
  transactionDate?: string
  description?: string
  particulars?: string
  transactionType?: TransactionType
  referenceNumber?: string
  isAutoGenerated?: boolean
  amount?: number
  transactionFee?: number
  transactionStatus?: TransactionStatus
  from?: string
  to?: string
  confidence?: number
  aiExtractedJson?: TransactionFormInput['aiExtractedJson']
  error?: string
}

function normalizeTransactionType(value: unknown): TransactionType | undefined {
  const normalized = String(value || '')
    .trim()
    .toLowerCase()

  if (normalized === 'debit' || normalized === 'credit') {
    return normalized
  }

  return undefined
}

function normalizeTransactionStatus(value: unknown): TransactionStatus | undefined {
  const normalized = String(value || '')
    .trim()
    .toLowerCase()

  if (normalized === 'completed' || normalized === 'failed') {
    return normalized
  }

  return undefined
}

function normalizeAmount(value: unknown): number | undefined {
  if (typeof value === 'number' && Number.isFinite(value)) {
    return value > 0 ? value : undefined
  }

  const parsed = Number(
    String(value || '')
      .replace(/,/g, '')
      .trim(),
  )
  if (Number.isFinite(parsed) && parsed > 0) {
    return parsed
  }

  return undefined
}

function normalizeNonNegativeAmount(value: unknown): number {
  if (typeof value === 'number' && Number.isFinite(value)) {
    return value >= 0 ? value : 0
  }

  const parsed = Number(
    String(value || '')
      .replace(/,/g, '')
      .trim(),
  )

  return Number.isFinite(parsed) && parsed >= 0 ? parsed : 0
}

function normalizeReferenceNumber(value: unknown): string | undefined {
  const normalized = String(value || '').trim()
  return normalized || undefined
}

function parseAiExtractedJsonValue(
  value: FormDataEntryValue | null,
): TransactionFormInput['aiExtractedJson'] {
  if (typeof value !== 'string') return undefined

  const raw = value.trim()
  if (!raw) return undefined

  try {
    return JSON.parse(raw) as TransactionFormInput['aiExtractedJson']
  } catch {
    return undefined
  }
}

function parseConfidenceValue(value: FormDataEntryValue | null): number | undefined {
  if (typeof value !== 'string') return undefined

  const parsed = Number(value.trim())
  if (!Number.isFinite(parsed)) return undefined

  return Math.max(0, Math.min(100, parsed))
}

async function isReferenceNumberTaken(args: {
  payload: Awaited<ReturnType<typeof getPayload>>
  referenceNumber?: string
  excludeTransactionId?: string
}): Promise<string | undefined> {
  const referenceNumber = normalizeReferenceNumber(args.referenceNumber)
  if (!referenceNumber) return undefined

  const where: Record<string, unknown> = {
    referenceNumber: {
      equals: referenceNumber,
    },
  }

  if (args.excludeTransactionId) {
    where.id = {
      not_equals: args.excludeTransactionId,
    }
  }

  const existing = await args.payload.find({
    collection: 'transactions',
    where: where as any,
    depth: 0,
    limit: 1,
    overrideAccess: true,
  })

  if (existing.totalDocs < 1 || existing.docs.length < 1) return undefined

  const first = existing.docs[0] as { id?: string | number }
  return first.id != null ? String(first.id) : undefined
}

// Use shared utility for base and suffix

async function generateUniqueAutoReferenceNumber(args: {
  payload: Awaited<ReturnType<typeof getPayload>>
  transactionDate?: string
  excludeTransactionId?: string
}): Promise<string> {
  const base = generateAutoReferenceNumberBase(args.transactionDate)

  for (let index = 0; index < 26 * 26; index += 1) {
    const candidate = `${base}${toAlphabetSuffix(index)}`
    const existing = await isReferenceNumberTaken({
      payload: args.payload,
      referenceNumber: candidate,
      excludeTransactionId: args.excludeTransactionId,
    })
    if (!existing) return candidate
  }

  throw new Error('Failed to generate unique reference number.')
}

function createReadableDescriptionFromParticulars(particulars?: string): string | undefined {
  const raw = String(particulars || '')
    .replace(/\s+/g, ' ')
    .trim()
  if (!raw) return undefined

  // Prefer explicit remarks/notes content when available.
  const notesOrRemarks = raw.match(/\b(?:notes?|remarks?)\s*[:\-]?\s*(.+)$/i)?.[1]?.trim()
  if (notesOrRemarks) {
    const cleaned = notesOrRemarks.replace(/[.\s]+$/, '')
    if (cleaned) {
      const normalized = cleaned.charAt(0).toUpperCase() + cleaned.slice(1)
      return `${normalized}.`
    }
  }

  const lower = raw.toLowerCase()
  if (lower.includes('send money') || lower.includes('instapay')) {
    const channel = raw.match(/via\s+([a-z0-9\- ]+?)\s+(to|from|notes?)\b/i)?.[1]?.trim()
    const toValue = raw.match(/\bto\s+([^\n]+?)(?:\s+from\b|\s+notes?\b|$)/i)?.[1]?.trim()
    const fromValue = raw.match(/\bfrom\s+([^\n]+?)(?:\s+notes?\b|$)/i)?.[1]?.trim()
    const notesValue = raw.match(/\bnotes?\s+(.+)$/i)?.[1]?.trim()

    const parts: string[] = []
    if (channel) {
      const normalizedChannel = channel.replace(/instapay/i, 'Instapay')
      parts.push(`Sent money via ${normalizedChannel}`)
    } else {
      parts.push('Sent money')
    }
    if (toValue) parts.push(`to ${toValue}`)
    if (fromValue) parts.push(`from ${fromValue}`)
    if (notesValue) parts.push(`for ${notesValue}`)

    const sentence = parts.join(' ').trim()
    if (sentence) return `${sentence}.`
  }

  return raw
}

function normalizeTransactionDate(
  value: unknown,
  options?: { boundary?: 'start' | 'end' },
): string | undefined {
  const raw = String(value || '').trim()
  if (!raw) return undefined

  const parsed = new Date(raw)
  if (Number.isNaN(parsed.getTime())) return undefined

  if (options?.boundary === 'start') {
    parsed.setHours(0, 0, 0, 0)
  }

  if (options?.boundary === 'end') {
    parsed.setHours(23, 59, 59, 999)
  }

  return parsed.toISOString()
}

const escapeRegexLikeValue = (value: string): string => {
  return value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')
}

async function createTransactionReceiptFromFormData(formData: FormData): Promise<{
  success: boolean
  id?: string
  url?: string
  rawOcrText?: string
  error?: string
}> {
  const file = formData.get('file')
  if (!(file instanceof File)) return { success: false, error: 'No file provided.' }

  const arrayBuffer = await file.arrayBuffer()
  const buffer = Buffer.from(arrayBuffer)
  const { rawText } = await extractTextFromImageBuffer(buffer)
  const payload = await getPayload({ config })

  const receipt = await payload.create({
    collection: 'transaction-receipts',
    data: {},
    file: {
      data: buffer,
      name: file.name,
      mimetype: file.type || 'image/jpeg',
      size: buffer.length,
    },
    depth: 0,
  })

  return {
    success: true,
    id: String(receipt.id),
    url: receipt.url
      ? String(receipt.url)
      : (receipt as any).filename
        ? `/api/transaction-receipts/file/${encodeURIComponent(String((receipt as any).filename))}`
        : undefined,
    rawOcrText: rawText,
  }
}

async function deleteTransactionReceiptById(id: string) {
  try {
    const payload = await getPayload({ config })
    await payload.delete({ collection: 'transaction-receipts', id })
  } catch (error) {
    console.error(`Failed to rollback transaction receipt ${id}:`, error)
  }
}

async function resolveSourceBankIdFromFinancialAccount(
  financialAccountId: string,
): Promise<{ bankId?: string; error?: string }> {
  const payload = await getPayload({ config })

  const financialAccount = await payload.findByID({
    collection: 'financial-accounts',
    id: financialAccountId,
    depth: 1,
  })

  const rawBank = (financialAccount as any).bank
  const bankId =
    rawBank && typeof rawBank === 'object'
      ? String(rawBank.id)
      : rawBank
        ? String(rawBank)
        : undefined

  if (!bankId) {
    return { error: 'Selected financial account has no linked bank.' }
  }

  return { bankId }
}

function normalizeTextToken(value: string): string {
  return value
    .toLowerCase()
    .replace(/[^a-z0-9]/g, ' ')
    .replace(/\s+/g, ' ')
    .trim()
}

function textContainsBankReference(
  value: string | undefined,
  bank: BankOption | undefined,
): boolean {
  if (!value || !bank) return false

  const normalizedText = ` ${normalizeTextToken(value)} `
  const codeToken = normalizeTextToken(bank.code)
  const nameToken = normalizeTextToken(bank.name)
  const shortNameToken = normalizeTextToken(bank.shortName || '')

  const codeMatch = codeToken.length >= 2 && normalizedText.includes(` ${codeToken} `)
  const nameMatch = nameToken.length >= 3 && normalizedText.includes(` ${nameToken} `)
  const shortNameMatch =
    shortNameToken.length >= 2 && normalizedText.includes(` ${shortNameToken} `)

  return codeMatch || nameMatch || shortNameMatch
}

function detectBankMentionFromText(
  value: string | undefined,
  banks: BankOption[],
): string | undefined {
  if (!value) return undefined
  return banks.find((bank) => textContainsBankReference(value, bank))?.id
}

function inferTransactionTypeFromBankContext(params: {
  extractedType?: TransactionType
  selectedBankId?: string
  detectedDestinationBankId?: string
  fromText?: string
  toText?: string
  banks: BankOption[]
}): TransactionType | undefined {
  const { extractedType, selectedBankId, detectedDestinationBankId, fromText, toText, banks } =
    params

  if (!selectedBankId) return extractedType

  // Strong signal: destination bank was identified and it is not the selected account bank.
  if (detectedDestinationBankId && detectedDestinationBankId !== selectedBankId) {
    return 'debit'
  }

  const mentionedToBankId = detectBankMentionFromText(toText, banks)
  const mentionedFromBankId = detectBankMentionFromText(fromText, banks)

  // User rule: if "to" clearly points to a different bank than selected account bank, classify as debit.
  if (mentionedToBankId && mentionedToBankId !== selectedBankId) {
    return 'debit'
  }

  // If "from" explicitly references the selected bank, treat it as credit unless a stronger rule matched.
  if (mentionedFromBankId && mentionedFromBankId === selectedBankId) {
    return 'credit'
  }

  return extractedType
}

function mapTransactionInput(
  input: TransactionFormInput & {
    amount: number
    transactionFee: number
    transactionType: TransactionType
    financialAccount?: string
  },
) {
  const resolvedParentTransaction =
    input.isAllocatedFund === true ? String(input.parentTransaction || '').trim() || null : null
  // Only allow valid values for allocatedFundType
  const validAllocatedFundType =
    input.allocatedFundType === 'completed' || input.allocatedFundType === 'returned'
      ? input.allocatedFundType
      : undefined
  return {
    transactionDate: normalizeTransactionDate(input.transactionDate),
    description: input.description.trim(),
    particulars: input.particulars?.trim() || undefined,
    transactionType: input.transactionType,
    sourceAccount: input.sourceAccount || undefined,
    destinationAccount: input.destinationAccount || undefined,
    financialAccount: input.financialAccount || '',
    from: input.from?.trim() || undefined,
    to: input.to?.trim() || undefined,
    referenceNumber: input.referenceNumber?.trim() || undefined,
    amount: input.amount,
    transactionFee: input.transactionFee,
    currentBalance:
      typeof input.currentBalance === 'number' && Number.isFinite(input.currentBalance)
        ? input.currentBalance
        : undefined,
    isAutoGenerated: input.isAutoGenerated === true,
    isForAllocation: input.isForAllocation === true,
    transactionStatus: normalizeTransactionStatus(input.transactionStatus) ?? 'completed',
    isAllocatedFund: input.isAllocatedFund ?? false,
    parentTransaction: resolvedParentTransaction,
    ...(typeof validAllocatedFundType !== 'undefined'
      ? { allocatedFundType: validAllocatedFundType }
      : {}),
    ...(input.receiptImageId ? { receiptImage: input.receiptImageId } : {}),
    ...(typeof input.rawOcrText !== 'undefined'
      ? {
          rawOcrText: input.rawOcrText || undefined,
          isAiGenerated: Boolean(input.rawOcrText),
        }
      : {}),
    ...(typeof input.aiExtractedJson !== 'undefined'
      ? {
          aiExtractedJson: input.aiExtractedJson,
        }
      : {}),
    ...(typeof input.extractionConfidence === 'number' &&
    Number.isFinite(input.extractionConfidence)
      ? {
          extractionConfidence: Math.max(0, Math.min(100, input.extractionConfidence)),
        }
      : {}),
  }
}

export async function getBanks(): Promise<{
  success: boolean
  data: BankOption[]
  error?: string
}> {
  try {
    const payload = await getPayload({ config })
    const result = await payload.find({
      collection: 'banks',
      sort: 'name',
      limit: 100,
      depth: 0,
    })

    return {
      success: true,
      data: (result.docs as any[]).map((doc) => ({
        id: String(doc.id),
        name: String(doc.name || ''),
        code: String(doc.code || ''),
      })),
    }
  } catch (error) {
    console.error('Failed to fetch banks:', error)
    return { success: false, data: [], error: 'Failed to load banks.' }
  }
}

export async function getFinancialAccounts(): Promise<{
  success: boolean
  data: FinancialAccountOption[]
  error?: string
}> {
  try {
    const payload = await getPayload({ config })
    const result = await payload.find({
      collection: 'financial-accounts',
      sort: 'name',
      limit: 100,
      depth: 1,
    })

    return {
      success: true,
      data: (result.docs as any[]).map((doc) => ({
        id: String(doc.id),
        name: String(doc.name || ''),
        code: String(doc.code || ''),
        isDefault: (doc as any).isDefault === true,
        bankId:
          doc.bank && typeof doc.bank === 'object'
            ? String(doc.bank.id)
            : doc.bank
              ? String(doc.bank)
              : undefined,
        bankName:
          doc.bank && typeof doc.bank === 'object' && doc.bank.name
            ? String(doc.bank.name)
            : undefined,
        bankShortName:
          doc.bank && typeof doc.bank === 'object' && doc.bank.shortName
            ? String(doc.bank.shortName)
            : undefined,
        startingBalance: typeof doc.startingBalance === 'number' ? doc.startingBalance : undefined,
        currentBalance: typeof doc.currentBalance === 'number' ? doc.currentBalance : undefined,
        allocationFunds: typeof doc.allocationFunds === 'number' ? doc.allocationFunds : undefined,
        allocatedFunds: typeof doc.allocatedFunds === 'number' ? doc.allocatedFunds : undefined,
      })),
    }
  } catch (error) {
    console.error('Failed to fetch financial accounts:', error)
    return { success: false, data: [], error: 'Failed to load financial accounts.' }
  }
}

export async function getTransactions(where?: Record<string, unknown>): Promise<{
  success: boolean
  data: TransactionListItem[]
  error?: string
}> {
  try {
    const payload = await getPayload({ config })
    const result = await payload.find({
      collection: 'transactions',
      sort: '-createdAt',
      limit: 1000,
      depth: 1,
      ...(where && { where: where as any }),
    })

    return {
      success: true,
      data: (result.docs as any[]).map((doc) => ({
        id: String(doc.id),
        description: String(doc.description || ''),
        particulars: doc.particulars ? String(doc.particulars) : undefined,
        transactionType: normalizeTransactionType(doc.transactionType),
        financialAccountId:
          doc.financialAccount && typeof doc.financialAccount === 'object'
            ? String(doc.financialAccount.id)
            : doc.financialAccount
              ? String(doc.financialAccount)
              : undefined,
        financialAccountName:
          doc.financialAccount &&
          typeof doc.financialAccount === 'object' &&
          doc.financialAccount.name
            ? String(doc.financialAccount.name)
            : undefined,
        sourceAccountName:
          doc.sourceAccount && typeof doc.sourceAccount === 'object' && doc.sourceAccount.name
            ? String(doc.sourceAccount.name)
            : undefined,
        sourceAccountCode:
          doc.sourceAccount && typeof doc.sourceAccount === 'object' && doc.sourceAccount.code
            ? String(doc.sourceAccount.code)
            : undefined,
        destinationAccountName:
          doc.destinationAccount &&
          typeof doc.destinationAccount === 'object' &&
          doc.destinationAccount.name
            ? String(doc.destinationAccount.name)
            : undefined,
        destinationAccountCode:
          doc.destinationAccount &&
          typeof doc.destinationAccount === 'object' &&
          doc.destinationAccount.code
            ? String(doc.destinationAccount.code)
            : undefined,
        from: doc.from ? String(doc.from) : undefined,
        to: doc.to ? String(doc.to) : undefined,
        sender: doc.sender ? String(doc.sender) : undefined,
        receiver: doc.receiver ? String(doc.receiver) : undefined,
        referenceNumber: doc.referenceNumber ? String(doc.referenceNumber) : undefined,
        isAutoGenerated: doc.isAutoGenerated === true,
        isAllocatedFund: doc.isAllocatedFund === true,
        isForAllocation: doc.isForAllocation === true,
        allocatedFunds: typeof doc.allocatedFunds === 'number' ? doc.allocatedFunds : 0,
        allocatedFundType:
          doc.allocatedFundType === 'completed' || doc.allocatedFundType === 'returned'
            ? doc.allocatedFundType
            : doc.allocatedFundType === null || typeof doc.allocatedFundType === 'undefined'
              ? null
              : undefined,
        parentTransaction:
          doc.parentTransaction && typeof doc.parentTransaction === 'object'
            ? String(doc.parentTransaction.id)
            : doc.parentTransaction
              ? String(doc.parentTransaction)
              : null,
        transactionDate: doc.transactionDate ? String(doc.transactionDate) : undefined,
        amount: typeof doc.amount === 'number' ? doc.amount : undefined,
        transactionFee: typeof doc.transactionFee === 'number' ? doc.transactionFee : 0,
        currentBalance: typeof doc.currentBalance === 'number' ? doc.currentBalance : undefined,
        runningBalance: typeof doc.runningBalance === 'number' ? doc.runningBalance : undefined,
        transactionStatus: normalizeTransactionStatus(doc.transactionStatus),
        createdAt: String(doc.createdAt || ''),
        lastUpdated: String(doc.lastUpdated || doc.createdAt || ''),
        receiptImage:
          doc.receiptImage && typeof doc.receiptImage === 'object'
            ? { url: doc.receiptImage.url || undefined }
            : undefined,
      })),
    }
  } catch (error) {
    console.error('Failed to fetch transactions:', error)
    return { success: false, data: [], error: 'Failed to load transactions.' }
  }
}

export async function getAllTransactionsForFinancialAccount(financialAccountId: string): Promise<{
  success: boolean
  data: TransactionListItem[]
  error?: string
}> {
  try {
    const normalizedId = String(financialAccountId || '').trim()
    if (!normalizedId) {
      return { success: false, data: [], error: 'Financial account is required.' }
    }

    const payload = await getPayload({ config })
    const docs: any[] = []
    let page = 1

    while (true) {
      const result = await payload.find({
        collection: 'transactions',
        where: {
          financialAccount: {
            equals: normalizedId,
          },
        },
        sort: 'transactionDate',
        limit: 200,
        page,
        depth: 1,
      })

      docs.push(...(result.docs as any[]))

      const currentPage = Number(result.page || 1)
      const totalPages = Number(result.totalPages || 1)
      if (currentPage >= totalPages) break
      page = currentPage + 1
    }

    return {
      success: true,
      data: docs.map((doc) => mapTransactionDocToListItem(doc)),
    }
  } catch (error) {
    console.error('Failed to fetch financial account transactions:', error)
    return { success: false, data: [], error: 'Failed to load transactions.' }
  }
}

const mapTransactionDocToListItem = (doc: any): TransactionListItem => ({
  id: String(doc.id),
  description: String(doc.description || ''),
  particulars: doc.particulars ? String(doc.particulars) : undefined,
  transactionType: normalizeTransactionType(doc.transactionType),
  financialAccountId:
    doc.financialAccount && typeof doc.financialAccount === 'object'
      ? String(doc.financialAccount.id)
      : doc.financialAccount
        ? String(doc.financialAccount)
        : undefined,
  financialAccountName:
    doc.financialAccount && typeof doc.financialAccount === 'object' && doc.financialAccount.name
      ? String(doc.financialAccount.name)
      : undefined,
  sourceAccountId:
    doc.sourceAccount && typeof doc.sourceAccount === 'object' && doc.sourceAccount.id
      ? String(doc.sourceAccount.id)
      : undefined,
  sourceAccountName:
    doc.sourceAccount && typeof doc.sourceAccount === 'object' && doc.sourceAccount.name
      ? String(doc.sourceAccount.name)
      : undefined,
  sourceAccountCode:
    doc.sourceAccount && typeof doc.sourceAccount === 'object' && doc.sourceAccount.code
      ? String(doc.sourceAccount.code)
      : undefined,
  destinationAccountId:
    doc.destinationAccount &&
    typeof doc.destinationAccount === 'object' &&
    doc.destinationAccount.id
      ? String(doc.destinationAccount.id)
      : undefined,
  destinationAccountName:
    doc.destinationAccount &&
    typeof doc.destinationAccount === 'object' &&
    doc.destinationAccount.name
      ? String(doc.destinationAccount.name)
      : undefined,
  destinationAccountCode:
    doc.destinationAccount &&
    typeof doc.destinationAccount === 'object' &&
    doc.destinationAccount.code
      ? String(doc.destinationAccount.code)
      : undefined,
  from: doc.from ? String(doc.from) : undefined,
  to: doc.to ? String(doc.to) : undefined,
  sender: doc.sender ? String(doc.sender) : undefined,
  receiver: doc.receiver ? String(doc.receiver) : undefined,
  referenceNumber: doc.referenceNumber ? String(doc.referenceNumber) : undefined,
  isAutoGenerated: doc.isAutoGenerated === true,
  isAllocatedFund: doc.isAllocatedFund === true,
  isForAllocation: doc.isForAllocation === true,
  allocatedFunds: typeof doc.allocatedFunds === 'number' ? doc.allocatedFunds : 0,
  allocatedFundType:
    doc.allocatedFundType === 'completed' || doc.allocatedFundType === 'returned'
      ? doc.allocatedFundType
      : doc.allocatedFundType === null || typeof doc.allocatedFundType === 'undefined'
        ? null
        : undefined,
  parentTransaction:
    doc.parentTransaction && typeof doc.parentTransaction === 'object'
      ? String(doc.parentTransaction.id)
      : doc.parentTransaction
        ? String(doc.parentTransaction)
        : null,
  transactionDate: doc.transactionDate ? String(doc.transactionDate) : undefined,
  amount: typeof doc.amount === 'number' ? doc.amount : undefined,
  transactionFee: typeof doc.transactionFee === 'number' ? doc.transactionFee : 0,
  currentBalance: typeof doc.currentBalance === 'number' ? doc.currentBalance : undefined,
  runningBalance: typeof doc.runningBalance === 'number' ? doc.runningBalance : undefined,
  transactionStatus: normalizeTransactionStatus(doc.transactionStatus),
  createdAt: String(doc.createdAt || ''),
  lastUpdated: String(doc.lastUpdated || ''),
  receiptImage:
    doc.receiptImage && typeof doc.receiptImage === 'object'
      ? { url: doc.receiptImage.url || undefined }
      : undefined,
})

export async function getTransactionsPage(
  params: GetTransactionsPageParams = {},
): Promise<TransactionPageResult> {
  try {
    const payload = await getPayload({ config })

    const page = Number.isInteger(params.page) && Number(params.page) > 0 ? Number(params.page) : 1
    const pageSize =
      Number.isInteger(params.pageSize) && Number(params.pageSize) > 0
        ? Number(params.pageSize)
        : 10

    const sortBy = params.sortBy || 'date'
    const sortOrder = params.sortOrder || 'desc'
    const sortField =
      sortBy === 'amount' ? 'amount' : sortBy === 'updated' ? 'lastUpdated' : 'transactionDate'
    const sort = `${sortOrder === 'asc' ? '' : '-'}${sortField}`

    const whereAnd: Record<string, unknown>[] = []

    const normalizedSearch = String(params.search || '').trim()
    if (normalizedSearch) {
      const uppercaseSearch = normalizedSearch.toUpperCase()
      const escapedSearch = escapeRegexLikeValue(normalizedSearch)
      whereAnd.push({
        or: [
          { referenceNumber: { equals: normalizedSearch } },
          { referenceNumber: { equals: uppercaseSearch } },
          { referenceNumber: { like: escapedSearch } },
        ],
      })
    }

    const financialAccountId = String(params.financialAccountId || '').trim()
    if (financialAccountId) {
      whereAnd.push({
        financialAccount: {
          equals: financialAccountId,
        },
      })
    }

    const typeFilters = (params.transactionTypes || []).filter(
      (value): value is TransactionType => value === 'debit' || value === 'credit',
    )
    if (typeFilters.length > 0) {
      whereAnd.push({
        transactionType: {
          in: typeFilters,
        },
      })
    }

    const statusFilters = (params.transactionStatuses || []).filter(
      (value): value is TransactionStatus => value === 'completed' || value === 'failed',
    )
    if (statusFilters.length > 0) {
      whereAnd.push({
        transactionStatus: {
          in: statusFilters,
        },
      })
    }

    const sourceAccountIds = Array.from(
      new Set(
        (params.sourceAccountIds || []).map((value) => String(value || '').trim()).filter(Boolean),
      ),
    )
    if (sourceAccountIds.length > 0) {
      whereAnd.push({
        sourceAccount: {
          in: sourceAccountIds,
        },
      })
    }

    const destinationAccountIds = Array.from(
      new Set(
        (params.destinationAccountIds || [])
          .map((value) => String(value || '').trim())
          .filter(Boolean),
      ),
    )
    if (destinationAccountIds.length > 0) {
      whereAnd.push({
        destinationAccount: {
          in: destinationAccountIds,
        },
      })
    }

    const normalizedStartDate = normalizeTransactionDate(params.startDate, { boundary: 'start' })
    if (normalizedStartDate) {
      whereAnd.push({
        transactionDate: {
          greater_than_equal: normalizedStartDate,
        },
      })
    }

    const normalizedEndDate = normalizeTransactionDate(params.endDate, { boundary: 'end' })
    if (normalizedEndDate) {
      whereAnd.push({
        transactionDate: {
          less_than_equal: normalizedEndDate,
        },
      })
    }

    const result = await payload.find({
      collection: 'transactions',
      sort,
      page,
      limit: pageSize,
      depth: 1,
      ...(whereAnd.length > 0
        ? {
            where: {
              and: whereAnd,
            } as any,
          }
        : {}),
    })

    return {
      success: true,
      data: (result.docs as any[]).map(mapTransactionDocToListItem),
      pagination: {
        page: Number(result.page || page),
        pageSize,
        totalDocs: Number(result.totalDocs || 0),
        totalPages: Number(result.totalPages || 1),
      },
    }
  } catch (error) {
    console.error('Failed to fetch transaction page:', error)
    return { success: false, data: [], error: 'Failed to load transactions.' }
  }
}

export async function searchNonCompletedAllocatedFunds(
  query: string,
  excludeTransactionId?: string,
): Promise<{
  success: boolean
  data: TransactionListItem[]
  error?: string
}> {
  try {
    const normalizedQuery = String(query || '').trim()
    if (normalizedQuery.length < 2) {
      return { success: true, data: [] }
    }

    const payload = await getPayload({ config })

    const whereClauses: Record<string, unknown>[] = [
      {
        parentTransaction: {
          exists: false,
        },
      },
      {
        or: [
          { referenceNumber: { like: normalizedQuery } },
          { description: { like: normalizedQuery } },
          { particulars: { like: normalizedQuery } },
          { from: { like: normalizedQuery } },
          { to: { like: normalizedQuery } },
        ],
      },
    ]

    const excludedId = String(excludeTransactionId || '').trim()
    if (excludedId) {
      whereClauses.push({
        id: {
          not_equals: excludedId,
        },
      })
    }

    const result = await payload.find({
      collection: 'transactions',
      where: {
        and: whereClauses,
      } as any,
      sort: '-transactionDate',
      limit: 20,
      depth: 1,
    })

    return {
      success: true,
      data: (result.docs as any[]).map((doc) => ({
        id: String(doc.id),
        description: String(doc.description || ''),
        particulars: doc.particulars ? String(doc.particulars) : undefined,
        transactionType: normalizeTransactionType(doc.transactionType),
        financialAccountId:
          doc.financialAccount && typeof doc.financialAccount === 'object'
            ? String(doc.financialAccount.id)
            : doc.financialAccount
              ? String(doc.financialAccount)
              : undefined,
        financialAccountName:
          doc.financialAccount &&
          typeof doc.financialAccount === 'object' &&
          doc.financialAccount.name
            ? String(doc.financialAccount.name)
            : undefined,
        sourceAccountId:
          doc.sourceAccount && typeof doc.sourceAccount === 'object' && doc.sourceAccount.id
            ? String(doc.sourceAccount.id)
            : undefined,
        sourceAccountName:
          doc.sourceAccount && typeof doc.sourceAccount === 'object' && doc.sourceAccount.name
            ? String(doc.sourceAccount.name)
            : undefined,
        sourceAccountCode:
          doc.sourceAccount && typeof doc.sourceAccount === 'object' && doc.sourceAccount.code
            ? String(doc.sourceAccount.code)
            : undefined,
        destinationAccountName:
          doc.destinationAccount &&
          typeof doc.destinationAccount === 'object' &&
          doc.destinationAccount.name
            ? String(doc.destinationAccount.name)
            : undefined,
        destinationAccountId:
          doc.destinationAccount &&
          typeof doc.destinationAccount === 'object' &&
          doc.destinationAccount.id
            ? String(doc.destinationAccount.id)
            : undefined,
        destinationAccountCode:
          doc.destinationAccount &&
          typeof doc.destinationAccount === 'object' &&
          doc.destinationAccount.code
            ? String(doc.destinationAccount.code)
            : undefined,
        from: doc.from ? String(doc.from) : undefined,
        to: doc.to ? String(doc.to) : undefined,
        sender: doc.sender ? String(doc.sender) : undefined,
        receiver: doc.receiver ? String(doc.receiver) : undefined,
        referenceNumber: doc.referenceNumber ? String(doc.referenceNumber) : undefined,
        isAutoGenerated: doc.isAutoGenerated === true,
        isAllocatedFund: doc.isAllocatedFund === true,
        allocatedFunds: typeof doc.allocatedFunds === 'number' ? doc.allocatedFunds : 0,
        parentTransaction:
          doc.parentTransaction && typeof doc.parentTransaction === 'object'
            ? String(doc.parentTransaction.id)
            : doc.parentTransaction
              ? String(doc.parentTransaction)
              : null,
        transactionDate: doc.transactionDate ? String(doc.transactionDate) : undefined,
        amount: typeof doc.amount === 'number' ? doc.amount : undefined,
        transactionFee: typeof doc.transactionFee === 'number' ? doc.transactionFee : 0,
        currentBalance: typeof doc.currentBalance === 'number' ? doc.currentBalance : undefined,
        runningBalance: typeof doc.runningBalance === 'number' ? doc.runningBalance : undefined,
        transactionStatus: normalizeTransactionStatus(doc.transactionStatus),
        createdAt: String(doc.createdAt || ''),
        lastUpdated: String(doc.lastUpdated || ''),
      })),
    }
  } catch (error) {
    console.error('Failed to search non-child transactions:', error)
    return { success: false, data: [], error: 'Failed to search transactions.' }
  }
}

export async function getUserTransactionTableColumnsConfig(): Promise<{
  success: boolean
  columns?: string[]
  error?: string
}> {
  try {
    const session = await auth.api.getSession({ headers: await headers() })
    if (!session?.user?.id) return { success: true, columns: undefined }

    const payload = await getPayload({ config })
    const result = await payload.find({
      collection: 'user-configurations',
      where: {
        user: {
          equals: session.user.id,
        },
      },
      depth: 0,
      limit: 1,
      overrideAccess: true,
    })

    const doc = result.docs[0] as any | undefined
    const savedColumns = doc?.transactionsConfig?.tableColumns

    return {
      success: true,
      columns: Array.isArray(savedColumns)
        ? savedColumns.map((column) => String(column || '').trim()).filter(Boolean)
        : undefined,
    }
  } catch (error) {
    console.error('Failed to fetch user transaction table columns config:', error)
    return { success: true, columns: undefined }
  }
}

export async function getUserTransactionPreviewTableColumnsConfig(): Promise<{
  success: boolean
  columns?: string[]
  error?: string
}> {
  try {
    const session = await auth.api.getSession({ headers: await headers() })
    if (!session?.user?.id) return { success: true, columns: undefined }

    const payload = await getPayload({ config })
    const result = await payload.find({
      collection: 'user-configurations',
      where: {
        user: {
          equals: session.user.id,
        },
      },
      depth: 0,
      limit: 1,
      overrideAccess: true,
    })

    const doc = result.docs[0] as any | undefined
    const savedColumns = doc?.transactionsConfig?.previewTableColumns

    return {
      success: true,
      columns: Array.isArray(savedColumns)
        ? savedColumns.map((column) => String(column || '').trim()).filter(Boolean)
        : undefined,
    }
  } catch (error) {
    console.error('Failed to fetch user transaction preview table columns config:', error)
    return { success: true, columns: undefined }
  }
}

export async function saveTransactionTableColumns(columns: string[]): Promise<{
  success: boolean
  error?: string
}> {
  try {
    const session = await auth.api.getSession({ headers: await headers() })
    if (!session?.user?.id) return { success: false, error: 'Unauthorized' }

    const allowedColumns = [
      'transactionDate',
      'description',
      'particulars',
      'transactionType',
      'sourceAccount',
      'destinationAccount',
      'financialAccount',
      'from',
      'to',
      'referenceNumber',
      'amount',
      'transactionFee',
      'sender',
      'receiver',
      'totalAmount',
      'currentBalance',
      'runningBalance',
      'transactionStatus',
      'receiptImage',
      'aiExtractedJson',
      'extractionConfidence',
      'isAllocatedFund',
      'isForAllocation',
      'allocatedFunds',
      'parentTransaction',
      'lastUpdated',
    ] as const

    type PersistedTableColumn = (typeof allowedColumns)[number]
    const allowedColumnSet = new Set<PersistedTableColumn>(allowedColumns)

    const sanitizedColumns: PersistedTableColumn[] = Array.from(
      new Set(
        columns
          .map((column) => String(column || '').trim())
          .filter((column) => column.length > 0)
          .filter((column): column is PersistedTableColumn =>
            allowedColumnSet.has(column as PersistedTableColumn),
          ),
      ),
    )

    const payload = await getPayload({ config })
    const existing = await payload.find({
      collection: 'user-configurations',
      where: {
        user: {
          equals: session.user.id,
        },
      },
      depth: 0,
      limit: 1,
      overrideAccess: true,
    })

    const existingDoc = existing.docs[0] as any | undefined

    if (existingDoc?.id) {
      await payload.update({
        collection: 'user-configurations',
        id: String(existingDoc.id),
        data: {
          transactionsConfig: {
            ...(existingDoc.transactionsConfig || {}),
            tableColumns: sanitizedColumns,
          },
        },
        depth: 0,
        overrideAccess: true,
      })
    } else {
      await payload.create({
        collection: 'user-configurations',
        data: {
          user: session.user.id,
          transactionsConfig: {
            tableColumns: sanitizedColumns,
          },
        },
        depth: 0,
        overrideAccess: true,
      })
    }

    return { success: true }
  } catch (error) {
    console.error('Failed to save transaction table columns:', error)
    return { success: false, error: 'Failed to save table columns configuration.' }
  }
}

export async function saveTransactionPreviewTableColumns(columns: string[]): Promise<{
  success: boolean
  error?: string
}> {
  try {
    const session = await auth.api.getSession({ headers: await headers() })
    if (!session?.user?.id) return { success: false, error: 'Unauthorized' }

    const allowedColumns = [
      'transactionDate',
      'description',
      'particulars',
      'transactionType',
      'sourceAccount',
      'destinationAccount',
      'financialAccount',
      'from',
      'to',
      'referenceNumber',
      'amount',
      'transactionFee',
      'sender',
      'receiver',
      'totalAmount',
      'currentBalance',
      'runningBalance',
      'transactionStatus',
      'receiptImage',
      'aiExtractedJson',
      'extractionConfidence',
      'isAllocatedFund',
      'isForAllocation',
      'allocatedFunds',
      'parentTransaction',
      'lastUpdated',
    ] as const

    type PersistedPreviewTableColumn = (typeof allowedColumns)[number]
    const allowedColumnSet = new Set<PersistedPreviewTableColumn>(allowedColumns)

    const sanitizedColumns: PersistedPreviewTableColumn[] = Array.from(
      new Set(
        columns
          .map((column) => String(column || '').trim())
          .filter((column) => column.length > 0)
          .filter((column): column is PersistedPreviewTableColumn =>
            allowedColumnSet.has(column as PersistedPreviewTableColumn),
          ),
      ),
    )

    const payload = await getPayload({ config })
    const existing = await payload.find({
      collection: 'user-configurations',
      where: {
        user: {
          equals: session.user.id,
        },
      },
      depth: 0,
      limit: 1,
      overrideAccess: true,
    })

    const existingDoc = existing.docs[0] as any | undefined

    if (existingDoc?.id) {
      await payload.update({
        collection: 'user-configurations',
        id: String(existingDoc.id),
        data: {
          transactionsConfig: {
            ...(existingDoc.transactionsConfig || {}),
            previewTableColumns: sanitizedColumns,
          },
        },
        depth: 0,
        overrideAccess: true,
      })
    } else {
      await payload.create({
        collection: 'user-configurations',
        data: {
          user: session.user.id,
          transactionsConfig: {
            previewTableColumns: sanitizedColumns,
          },
        },
        depth: 0,
        overrideAccess: true,
      })
    }

    return { success: true }
  } catch (error) {
    console.error('Failed to save transaction preview table columns:', error)
    return { success: false, error: 'Failed to save preview table columns configuration.' }
  }
}

export async function createTransaction(input: TransactionFormInput): Promise<{
  success: boolean
  id?: string
  error?: string
  existingTransactionId?: string
}> {
  try {
    const session = await auth.api.getSession({ headers: await headers() })
    if (!session?.user?.id) return { success: false, error: 'Unauthorized' }

    const description = input.description.trim()
    const transactionType = normalizeTransactionType(input.transactionType)
    const amount = normalizeAmount(input.amount)
    const transactionFee = normalizeNonNegativeAmount(input.transactionFee)
    const financialAccount = String(input.financialAccount || '').trim()
    const parentTransaction = String(input.parentTransaction || '').trim()
    const providedSourceAccount = String(input.sourceAccount || '').trim()

    if (!transactionType) return { success: false, error: 'Transaction type is required.' }
    if (!amount) return { success: false, error: 'Amount must be greater than zero.' }
    if (!financialAccount && !parentTransaction) {
      return { success: false, error: 'Financial account is required.' }
    }

    let resolvedSourceAccount = providedSourceAccount || undefined
    if (!resolvedSourceAccount) {
      return { success: false, error: 'Source bank is required.' }
    }

    const payload = await getPayload({ config })
    let resolvedReferenceNumber = normalizeReferenceNumber(input.referenceNumber)
    let isAutoGenerated = input.isAutoGenerated === true

    if (!resolvedReferenceNumber) {
      resolvedReferenceNumber = await generateUniqueAutoReferenceNumber({
        payload,
        transactionDate: new Date().toISOString(),
      })
      isAutoGenerated = true
    }

    const existingTransactionId = await isReferenceNumberTaken({
      payload,
      referenceNumber: resolvedReferenceNumber,
    })

    if (existingTransactionId) {
      return {
        success: false,
        error: 'Reference number already exists.',
        existingTransactionId,
      }
    }

    const doc = await payload.create({
      collection: 'transactions',
      draft: false,
      data: mapTransactionInput({
        ...input,
        referenceNumber: resolvedReferenceNumber,
        isAutoGenerated,
        sourceAccount: resolvedSourceAccount,
        description,
        transactionType,
        amount,
        transactionFee,
        ...(financialAccount ? { financialAccount } : {}),
        ...(typeof input.allocatedFundType !== 'undefined'
          ? { allocatedFundType: input.allocatedFundType }
          : {}),
      }),
      depth: 0,
    })

    return { success: true, id: String(doc.id) }
  } catch (error) {
    console.error('Failed to create transaction:', error)
    return { success: false, error: 'Failed to create transaction.' }
  }
}

export async function createTransactionWithReceipt(formData: FormData): Promise<{
  success: boolean
  id?: string
  error?: string
  existingTransactionId?: string
}> {
  try {
    const session = await auth.api.getSession({ headers: await headers() })
    if (!session?.user?.id) return { success: false, error: 'Unauthorized' }
    const description = String(formData.get('description') || '').trim()
    const file = formData.get('file')
    const hasFile = file instanceof File && file.size > 0
    let receiptResult:
      | {
          success: boolean
          id?: string
          url?: string
          rawOcrText?: string
          error?: string
        }
      | undefined
    if (hasFile) {
      receiptResult = await createTransactionReceiptFromFormData(formData)
      if (!receiptResult.success || !receiptResult.id) {
        return { success: false, error: receiptResult.error ?? 'Failed to save receipt.' }
      }
    }
    const rawOcrText =
      String(formData.get('rawOcrText') || '').trim() || receiptResult?.rawOcrText || undefined
    const financialAccount = String(formData.get('financialAccount') || '').trim() || undefined
    const aiExtractedJson = parseAiExtractedJsonValue(formData.get('aiExtractedJson'))
    const extractionConfidence = parseConfidenceValue(formData.get('extractionConfidence'))
    const isAllocatedFund = String(formData.get('isAllocatedFund') || '').trim() === 'true'
    const isForAllocation = String(formData.get('isForAllocation') || '').trim() === 'true'
    const parentTransaction = isAllocatedFund
      ? String(formData.get('parentTransaction') || '').trim() || null
      : null
    // Only allow valid values for allocatedFundType
    const allocatedFundTypeRaw = String(formData.get('allocatedFundType') || '').trim()
    const allocatedFundType: 'completed' | 'returned' | null | undefined =
      allocatedFundTypeRaw === 'completed' || allocatedFundTypeRaw === 'returned'
        ? allocatedFundTypeRaw
        : undefined
    const createResult = await createTransaction({
      transactionDate: String(formData.get('transactionDate') || '').trim() || undefined,
      description,
      particulars: String(formData.get('particulars') || '').trim() || undefined,
      transactionType: normalizeTransactionType(formData.get('transactionType')),
      sourceAccount: String(formData.get('sourceAccount') || '').trim() || undefined,
      destinationAccount: String(formData.get('destinationAccount') || '').trim() || undefined,
      financialAccount,
      from: String(formData.get('from') || '').trim() || undefined,
      to: String(formData.get('to') || '').trim() || undefined,
      referenceNumber: String(formData.get('referenceNumber') || '').trim() || undefined,
      isAutoGenerated: String(formData.get('isAutoGenerated') || '').trim() === 'true',
      amount: normalizeAmount(formData.get('amount')),
      transactionFee: normalizeNonNegativeAmount(formData.get('transactionFee')),
      currentBalance: normalizeNonNegativeAmount(formData.get('currentBalance')),
      transactionStatus: normalizeTransactionStatus(formData.get('transactionStatus')),
      receiptImageId: receiptResult?.id,
      rawOcrText,
      aiExtractedJson,
      extractionConfidence,
      isAllocatedFund,
      isForAllocation,
      parentTransaction,
      allocatedFundType,
    })
    if (!createResult.success && receiptResult?.id) {
      await deleteTransactionReceiptById(receiptResult.id)
    }
    return createResult
  } catch (error) {
    console.error('Failed to create transaction with receipt:', error)
    return { success: false, error: 'Failed to create transaction.' }
  }
}

export async function getTransactionById(id: string): Promise<{
  success: boolean
  data?: TransactionDetail
  error?: string
}> {
  try {
    const session = await auth.api.getSession({ headers: await headers() })
    if (!session?.user?.id) return { success: false, error: 'Unauthorized' }

    const payload = await getPayload({ config })
    const doc = await payload.findByID({
      collection: 'transactions',
      id,
      depth: 1,
      overrideAccess: true,
    })

    let receiptImageId: string | undefined
    let receiptImageUrl: string | undefined
    let receiptImageFileName: string | undefined

    if ((doc as any).receiptImage) {
      if (typeof (doc as any).receiptImage === 'string') {
        receiptImageId = String((doc as any).receiptImage)
      } else {
        receiptImageId = String((doc as any).receiptImage.id)

        receiptImageFileName = (doc as any).receiptImage.filename
          ? String((doc as any).receiptImage.filename)
          : undefined

        receiptImageUrl = (doc as any).receiptImage.url
          ? String((doc as any).receiptImage.url)
          : undefined
      }

      if (receiptImageId && (!receiptImageUrl || !receiptImageFileName)) {
        try {
          const receiptDoc = await payload.findByID({
            collection: 'transaction-receipts',
            id: receiptImageId,
            depth: 0,
            overrideAccess: true,
          })

          if (!receiptImageFileName && (receiptDoc as any).filename) {
            receiptImageFileName = String((receiptDoc as any).filename)
          }
          if (!receiptImageUrl && (receiptDoc as any).url) {
            receiptImageUrl = String((receiptDoc as any).url)
          }
        } catch (error) {
          console.error('[LOG 22] ERROR - Failed to hydrate receipt image metadata:', error)
        }
      }

      if (!receiptImageUrl && receiptImageId) {
        receiptImageUrl = `/api/transaction-receipts/${encodeURIComponent(receiptImageId)}`
      }
    } else {
    }

    return {
      success: true,
      data: {
        id: String((doc as any).id),
        transactionDate: (doc as any).transactionDate
          ? String((doc as any).transactionDate)
          : undefined,
        description: String((doc as any).description || ''),
        particulars: (doc as any).particulars ? String((doc as any).particulars) : undefined,
        transactionType: normalizeTransactionType((doc as any).transactionType),
        sourceAccount:
          (doc as any).sourceAccount && typeof (doc as any).sourceAccount === 'object'
            ? String((doc as any).sourceAccount.id)
            : (doc as any).sourceAccount
              ? String((doc as any).sourceAccount)
              : undefined,
        destinationAccount:
          (doc as any).destinationAccount && typeof (doc as any).destinationAccount === 'object'
            ? String((doc as any).destinationAccount.id)
            : (doc as any).destinationAccount
              ? String((doc as any).destinationAccount)
              : undefined,
        financialAccount:
          (doc as any).financialAccount && typeof (doc as any).financialAccount === 'object'
            ? String((doc as any).financialAccount.id)
            : (doc as any).financialAccount
              ? String((doc as any).financialAccount)
              : undefined,
        from: (doc as any).from ? String((doc as any).from) : undefined,
        to: (doc as any).to ? String((doc as any).to) : undefined,
        referenceNumber: (doc as any).referenceNumber
          ? String((doc as any).referenceNumber)
          : undefined,
        amount: typeof (doc as any).amount === 'number' ? (doc as any).amount : undefined,
        transactionFee:
          typeof (doc as any).transactionFee === 'number' ? (doc as any).transactionFee : 0,
        transactionStatus:
          normalizeTransactionStatus((doc as any).transactionStatus) ?? 'completed',
        receiptImageId,
        receiptImageUrl,
        receiptImageFileName,
        rawOcrText: (doc as any).rawOcrText ? String((doc as any).rawOcrText) : undefined,
        extractionConfidence:
          typeof (doc as any).extractionConfidence === 'number'
            ? (doc as any).extractionConfidence
            : undefined,
        aiExtractedJson: (doc as any).aiExtractedJson,
        isAiGenerated: (doc as any).isAiGenerated === true,
        isUserEdited: (doc as any).isUserEdited === true,
        runningBalance:
          typeof (doc as any).runningBalance === 'number' ? (doc as any).runningBalance : undefined,
        isAutoGenerated: (doc as any).isAutoGenerated === true,
        isAllocatedFund: (doc as any).isAllocatedFund === true,
        isForAllocation: (doc as any).isForAllocation === true,
        allocatedFunds:
          typeof (doc as any).allocatedFunds === 'number' ? (doc as any).allocatedFunds : 0,
        parentTransaction:
          (doc as any).parentTransaction && typeof (doc as any).parentTransaction === 'object'
            ? String((doc as any).parentTransaction.id)
            : (doc as any).parentTransaction
              ? String((doc as any).parentTransaction)
              : null,
        allocatedFundType:
          (doc as any).allocatedFundType === 'completed' ||
          (doc as any).allocatedFundType === 'returned'
            ? (doc as any).allocatedFundType
            : undefined,
      },
    }
  } catch (error) {
    console.error('Failed to fetch transaction:', error)
    return { success: false, error: 'Failed to load transaction.' }
  }
}

export async function updateTransaction(
  id: string,
  input: TransactionFormInput,
): Promise<{ success: boolean; error?: string; existingTransactionId?: string }> {
  try {
    const session = await auth.api.getSession({ headers: await headers() })
    if (!session?.user?.id) return { success: false, error: 'Unauthorized' }

    const description = input.description.trim()
    const transactionType = normalizeTransactionType(input.transactionType)
    const amount = normalizeAmount(input.amount)
    const transactionFee = normalizeNonNegativeAmount(input.transactionFee)
    const financialAccount = String(input.financialAccount || '').trim()
    const parentTransaction = String(input.parentTransaction || '').trim()
    const providedSourceAccount = String(input.sourceAccount || '').trim()

    if (!transactionType) return { success: false, error: 'Transaction type is required.' }
    if (!amount) return { success: false, error: 'Amount must be greater than zero.' }
    if (!financialAccount && !parentTransaction) {
      return { success: false, error: 'Financial account is required.' }
    }

    let resolvedSourceAccount = providedSourceAccount || undefined
    if (!resolvedSourceAccount) {
      return { success: false, error: 'Source bank is required.' }
    }

    const payload = await getPayload({ config })
    const currentDoc = (await payload.findByID({
      collection: 'transactions',
      id,
      depth: 0,
      overrideAccess: true,
    })) as { referenceNumber?: unknown; isAutoGenerated?: unknown }

    const currentReferenceNumber = normalizeReferenceNumber(currentDoc.referenceNumber)
    const incomingReferenceNumber = normalizeReferenceNumber(input.referenceNumber)
    let resolvedReferenceNumber = incomingReferenceNumber
    let isAutoGenerated = false

    if (!resolvedReferenceNumber) {
      resolvedReferenceNumber = await generateUniqueAutoReferenceNumber({
        payload,
        transactionDate: new Date().toISOString(),
        excludeTransactionId: id,
      })
      isAutoGenerated = true
    } else if (
      currentDoc.isAutoGenerated === true &&
      currentReferenceNumber &&
      resolvedReferenceNumber === currentReferenceNumber
    ) {
      isAutoGenerated = true
    }

    const existingTransactionId = await isReferenceNumberTaken({
      payload,
      referenceNumber: resolvedReferenceNumber,
      excludeTransactionId: id,
    })

    if (existingTransactionId) {
      return {
        success: false,
        error: 'Reference number already exists.',
        existingTransactionId,
      }
    }

    await payload.update({
      collection: 'transactions',
      id,
      data: mapTransactionInput({
        ...input,
        referenceNumber: resolvedReferenceNumber,
        isAutoGenerated,
        sourceAccount: resolvedSourceAccount,
        description,
        transactionType,
        amount,
        transactionFee,
        ...(financialAccount ? { financialAccount } : {}),
        ...(typeof input.allocatedFundType !== 'undefined'
          ? { allocatedFundType: input.allocatedFundType }
          : {}),
      }),
      depth: 0,
    })

    return { success: true }
  } catch (error) {
    console.error('Failed to update transaction:', error)
    return { success: false, error: 'Failed to update transaction.' }
  }
}

export async function updateTransactionWithReceipt(
  id: string,
  formData: FormData,
): Promise<{ success: boolean; error?: string; existingTransactionId?: string }> {
  try {
    const session = await auth.api.getSession({ headers: await headers() })
    if (!session?.user?.id) return { success: false, error: 'Unauthorized' }

    const payload = await getPayload({ config })
    const currentTx = await payload.findByID({
      collection: 'transactions',
      id,
      depth: 0,
    })

    const existingReceiptImageId = (currentTx as any).receiptImage
      ? typeof (currentTx as any).receiptImage === 'string'
        ? String((currentTx as any).receiptImage)
        : String((currentTx as any).receiptImage.id)
      : undefined

    let receiptImageId = String(formData.get('existingReceiptImageId') || '').trim() || undefined
    let rawOcrText = String(formData.get('rawOcrText') || '').trim() || undefined

    const nextReceipt = formData.get('file')
    if (nextReceipt instanceof File && nextReceipt.size > 0) {
      const receiptResult = await createTransactionReceiptFromFormData(formData)
      if (!receiptResult.success || !receiptResult.id) {
        return { success: false, error: receiptResult.error ?? 'Failed to save receipt.' }
      }

      if (existingReceiptImageId) {
        await deleteTransactionReceiptById(existingReceiptImageId)
      }

      receiptImageId = receiptResult.id
      rawOcrText = receiptResult.rawOcrText
    } else if (!receiptImageId && existingReceiptImageId) {
      await deleteTransactionReceiptById(existingReceiptImageId)
    }

    const financialAccount = String(formData.get('financialAccount') || '').trim() || undefined
    const aiExtractedJson = parseAiExtractedJsonValue(formData.get('aiExtractedJson'))
    const extractionConfidence = parseConfidenceValue(formData.get('extractionConfidence'))
    const isAllocatedFund = String(formData.get('isAllocatedFund') || '').trim() === 'true'
    const isForAllocation = String(formData.get('isForAllocation') || '').trim() === 'true'
    const parentTransaction = isAllocatedFund
      ? String(formData.get('parentTransaction') || '').trim() || null
      : null
    // Only allow valid values for allocatedFundType
    const allocatedFundTypeRaw = String(formData.get('allocatedFundType') || '').trim()
    const allocatedFundType: 'completed' | 'returned' | null | undefined =
      allocatedFundTypeRaw === 'completed' || allocatedFundTypeRaw === 'returned'
        ? allocatedFundTypeRaw
        : undefined
    return await updateTransaction(id, {
      transactionDate: String(formData.get('transactionDate') || '').trim() || undefined,
      description: String(formData.get('description') || '').trim(),
      particulars: String(formData.get('particulars') || '').trim() || undefined,
      transactionType: normalizeTransactionType(formData.get('transactionType')),
      sourceAccount: String(formData.get('sourceAccount') || '').trim() || undefined,
      destinationAccount: String(formData.get('destinationAccount') || '').trim() || undefined,
      financialAccount,
      from: String(formData.get('from') || '').trim() || undefined,
      to: String(formData.get('to') || '').trim() || undefined,
      referenceNumber: String(formData.get('referenceNumber') || '').trim() || undefined,
      isAutoGenerated: String(formData.get('isAutoGenerated') || '').trim() === 'true',
      amount: normalizeAmount(formData.get('amount')),
      transactionFee: normalizeNonNegativeAmount(formData.get('transactionFee')),
      currentBalance: normalizeNonNegativeAmount(formData.get('currentBalance')),
      transactionStatus: normalizeTransactionStatus(formData.get('transactionStatus')),
      receiptImageId,
      rawOcrText,
      aiExtractedJson,
      extractionConfidence,
      isAllocatedFund,
      isForAllocation,
      parentTransaction,
      allocatedFundType,
    })
  } catch (error) {
    console.error('Failed to update transaction with receipt:', error)
    return { success: false, error: 'Failed to update transaction.' }
  }
}

export async function deleteTransaction(id: string): Promise<{ success: boolean; error?: string }> {
  try {
    const session = await auth.api.getSession({ headers: await headers() })
    if (!session?.user?.id) return { success: false, error: 'Unauthorized' }

    const payload = await getPayload({ config })
    await payload.delete({ collection: 'transactions', id })
    return { success: true }
  } catch (error) {
    const message = error instanceof Error ? error.message : 'Failed to delete transaction.'
    return { success: false, error: message }
  }
}

export async function analyzeReceiptFile(formData: FormData): Promise<ReceiptAnalysisResult> {
  try {
    const session = await auth.api.getSession({ headers: await headers() })
    if (!session?.user?.id) return { success: false, error: 'Unauthorized' }

    const file = formData.get('file')
    if (!(file instanceof File)) return { success: false, error: 'No file provided.' }

    const arrayBuffer = await file.arrayBuffer()
    const buffer = Buffer.from(arrayBuffer)
    const { rawText } = await extractTextFromImageBuffer(buffer)
    const payload = await getPayload({ config })
    const banksResult = await getBanks()
    const selectedFinancialAccountId = String(formData.get('financialAccount') || '').trim()

    const sourceBankResolution = selectedFinancialAccountId
      ? await resolveSourceBankIdFromFinancialAccount(selectedFinancialAccountId)
      : { bankId: undefined }

    try {
      const extraction = await extractTransactionWithGroq({
        rawOcrText: rawText,
        banks: banksResult.data,
      })

      const readableDescription =
        createReadableDescriptionFromParticulars(extraction.extracted.particulars) ??
        extraction.extracted.description

      const detectedSourceBank = banksResult.data.find(
        (bank) => bank.code === extraction.detectedSourceBankCode,
      )
      const detectedDestinationBank = banksResult.data.find(
        (bank) => bank.code === extraction.detectedDestinationBankCode,
      )

      const inferredTransactionType = inferTransactionTypeFromBankContext({
        extractedType: extraction.extracted.transactionType,
        selectedBankId: sourceBankResolution.bankId,
        detectedDestinationBankId: detectedDestinationBank?.id,
        fromText: extraction.extracted.from,
        toText: extraction.extracted.to,
        banks: banksResult.data,
      })

      const extractedReferenceNumber = normalizeReferenceNumber(
        extraction.extracted.referenceNumber,
      )
      const autoGeneratedReferenceNumber = !extractedReferenceNumber
        ? await generateUniqueAutoReferenceNumber({
            payload,
            transactionDate: new Date().toISOString(),
          })
        : undefined

      return {
        success: true,
        rawOcrText: rawText,
        detectedSourceBankId: detectedSourceBank?.id,
        detectedDestinationBankId: detectedDestinationBank?.id,
        transactionDate: extraction.extracted.transactionDate,
        description: readableDescription,
        particulars: extraction.extracted.particulars ?? extraction.extracted.description,
        transactionType: inferredTransactionType,
        referenceNumber: extractedReferenceNumber || autoGeneratedReferenceNumber,
        isAutoGenerated: !extractedReferenceNumber,
        amount: extraction.extracted.amount,
        transactionFee: extraction.extracted.transactionFee ?? 0,
        transactionStatus: extraction.extracted.transactionStatus,
        from: extraction.extracted.from,
        to: extraction.extracted.to,
        confidence: extraction.confidence,
        aiExtractedJson: extraction.rawJson as TransactionFormInput['aiExtractedJson'],
      }
    } catch (groqError) {
      const errMsg = groqError instanceof Error ? groqError.message : String(groqError)
      console.error('Groq extraction failed during file analysis:', errMsg)
      return {
        success: false,
        rawOcrText: rawText,
        error: `AI extraction failed: ${errMsg}`,
      }
    }
  } catch (error) {
    console.error('Failed to analyze receipt file:', error)
    return { success: false, error: 'Failed to analyze receipt.' }
  }
}

export async function processTransactionReceipt(
  transactionId: string,
): Promise<ProcessTransactionReceiptResult> {
  try {
    const session = await auth.api.getSession({ headers: await headers() })
    if (!session?.user?.id) {
      return { success: false, status: 'failed', error: 'Unauthorized' }
    }

    const payload = await getPayload({ config })
    const tx = await payload.findByID({
      collection: 'transactions',
      id: transactionId,
      depth: 1,
      overrideAccess: true,
    })

    const receipt = (tx as any).receiptImage
    if (!receipt) {
      return {
        success: false,
        status: 'failed',
        error: 'Receipt image is required before processing.',
      }
    }

    const receiptImageId = typeof receipt === 'string' ? receipt : String(receipt.id)
    let receiptImageFileName: string | undefined
    let receiptImageUrl: string | undefined =
      typeof receipt === 'object' && receipt.url ? String(receipt.url) : undefined

    if (typeof receipt === 'object' && receipt.filename) {
      receiptImageFileName = String(receipt.filename)
    }

    if (!receiptImageUrl || !receiptImageFileName) {
      try {
        const receiptDoc = await payload.findByID({
          collection: 'transaction-receipts',
          id: receiptImageId,
          depth: 0,
          overrideAccess: true,
        })

        if (!receiptImageFileName && (receiptDoc as any).filename) {
          receiptImageFileName = String((receiptDoc as any).filename)
        }
        if (!receiptImageUrl && (receiptDoc as any).url) {
          receiptImageUrl = String((receiptDoc as any).url)
        }
      } catch (error) {
        console.error('Failed to resolve receipt image for processing:', error)
      }
    }

    if (!receiptImageUrl && receiptImageFileName) {
      receiptImageUrl = `/api/transaction-receipts/file/${encodeURIComponent(receiptImageFileName)}`
    }
    if (!receiptImageUrl) {
      return {
        success: false,
        status: 'failed',
        error: 'Could not resolve receipt image URL.',
      }
    }

    let rawOcrText = (tx as any).rawOcrText ? String((tx as any).rawOcrText) : ''

    if (!rawOcrText.trim()) {
      const resolvedImageUrl = receiptImageUrl.startsWith('http')
        ? receiptImageUrl
        : `${getServerSideURL()}${receiptImageUrl}`

      const imageResponse = await fetch(resolvedImageUrl)
      if (!imageResponse.ok) {
        return {
          success: false,
          status: 'failed',
          error: `Failed to fetch receipt image (${imageResponse.status}).`,
        }
      }

      const imageBuffer = Buffer.from(await imageResponse.arrayBuffer())
      const ocrResult = await extractTextFromImageBuffer(imageBuffer)
      rawOcrText = ocrResult.rawText
    }

    const banksResult = await getBanks()

    try {
      const extraction = await extractTransactionWithGroq({
        rawOcrText,
        banks: banksResult.data,
      })

      const readableDescription =
        createReadableDescriptionFromParticulars(extraction.extracted.particulars) ??
        extraction.extracted.description

      const destinationBank = banksResult.data.find(
        (bank) => bank.code === extraction.detectedDestinationBankCode,
      )

      const txFinancialAccountId =
        (tx as any).financialAccount && typeof (tx as any).financialAccount === 'object'
          ? String((tx as any).financialAccount.id)
          : (tx as any).financialAccount
            ? String((tx as any).financialAccount)
            : ''

      const sourceBankResolution = txFinancialAccountId
        ? await resolveSourceBankIdFromFinancialAccount(txFinancialAccountId)
        : { bankId: undefined }

      const inferredTransactionType = inferTransactionTypeFromBankContext({
        extractedType: extraction.extracted.transactionType,
        selectedBankId: sourceBankResolution.bankId,
        detectedDestinationBankId: destinationBank?.id,
        fromText: extraction.extracted.from,
        toText: extraction.extracted.to,
        banks: banksResult.data,
      })

      const extractedReferenceNumber = normalizeReferenceNumber(
        extraction.extracted.referenceNumber,
      )
      const autoGeneratedReferenceNumber = !extractedReferenceNumber
        ? await generateUniqueAutoReferenceNumber({
            payload,
            transactionDate: new Date().toISOString(),
            excludeTransactionId: transactionId,
          })
        : undefined

      return {
        success: true,
        status: 'success',
        rawOcrText,
        detectedSourceBankId: sourceBankResolution.bankId,
        detectedDestinationBankId: destinationBank?.id,
        transactionDate: extraction.extracted.transactionDate,
        description: readableDescription,
        particulars: extraction.extracted.particulars ?? extraction.extracted.description,
        transactionType: inferredTransactionType,
        referenceNumber: extractedReferenceNumber || autoGeneratedReferenceNumber,
        isAutoGenerated: !extractedReferenceNumber,
        amount: extraction.extracted.amount,
        transactionFee: extraction.extracted.transactionFee ?? 0,
        transactionStatus: extraction.extracted.transactionStatus,
        from: extraction.extracted.from,
        to: extraction.extracted.to,
        confidence: extraction.confidence,
        aiExtractedJson: extraction.rawJson as TransactionFormInput['aiExtractedJson'],
      }
    } catch (error) {
      const errMsg = error instanceof Error ? error.message : String(error)
      console.error('Groq extraction failed:', errMsg)
      return {
        success: false,
        status: rawOcrText.trim() ? 'partial-success' : 'failed',
        rawOcrText: rawOcrText.trim() ? rawOcrText : undefined,
        error: `AI extraction failed: ${errMsg}`,
      }
    }
  } catch (error) {
    console.error('Failed to process transaction receipt:', error)
    return { success: false, status: 'failed', error: 'Failed to process receipt.' }
  }
}
