'use client'

import { CSSVariablesResolver, MantineProvider, createTheme } from '@mantine/core'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

const theme = createTheme({
  spacing: {
    xl: '3rem',
  },
})

const resolver: CSSVariablesResolver = (theme) => ({
  variables: {},
  light: {
    '--light-bg-0': theme.colors.gray[0],
  },
  dark: {
    '--light-bg-0': theme.colors.dark[9],
  },
})

export const ThemeProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  return (
    <MantineProvider theme={theme} cssVariablesResolver={resolver}>
      {children}
    </MantineProvider>
  )
}
